API/urls.py
from django.urls import path

from API import views
from API.views import EventDetailApiView, EventListApiView, detail_api_view

app_name = 'api'

urlpatterns = [
    path('get_events/', views.get_events, name ='get_events'),

    path('events/', views.EventListView.as_view(), name='event_list'),
    path('events/<pk>/',views.EventDetailView.as_view(), name='event_detail'),
    path('', EventListApiView.as_view(), name = 'list_api_view'),
    path('<int:event_id>/', EventDetailApiView.as_view()),
    path('detail_api_view', detail_api_view, name='detail_api_view')
    ]

EventAggregationService/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy

from EventViewer.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home_page'),
    path('events/', event_page, name='event_page'),
    path('event_detail/<pk>/', event_detail_page, name='event_detail_page'),
    path('search_events/', search_events, name='search_events'),
    path('filter_events/', filter_events, name='filter_events'),

    #attending
    path('attend/', attend_event, name='attend_event'),

    #add, edit , delete event
    path('new_event/', EventCreateView.as_view(), name='new_event'),
    path('event/update/<pk>/', EventUpdateView.as_view(), name='update_event'),
    path('delete_event/<pk>/', EventDeleteView.as_view(), name='delete_event'),

    #comments
    path('add_comment/<pk>/', add_comment, name='add_comment'),
    path('edit_comment/<pk>', edit_comment, name='edit_comment'),
    path('delete_comment/<pk>/', delete_comment, name='delete_comment'),

    #users
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),

    #API
    path('api/', include('API.urls', namespace='api')),

]

EventViewer/models.py
from django.contrib.auth.models import User
from django.db.models import *


# Create your models here.

class Category(Model):
    name = CharField(max_length=50)

    def __str__(self):
        return self.name


class Event(Model):
    name = CharField(max_length=50)
    category = ForeignKey(Category, on_delete=DO_NOTHING)
    city = CharField(max_length=50)
    price = FloatField()
    start_at = DateTimeField()
    end_at = DateTimeField(null=True)
    link = CharField(max_length=200)
    picture = CharField(max_length=200)
    description = TextField(max_length=1024)
    user_attend = ManyToManyField(User, related_name='attending_user', blank=True)
    user_creator = ForeignKey(User, on_delete=DO_NOTHING, null=True)

    class Meta:
        ordering = ['start_at']

    def __str__(self):
        return self.name


class Comment(Model):
    event = ForeignKey(Event, null=False, on_delete=CASCADE, related_name='event_comment')
    user = ForeignKey(User, null=False, on_delete=CASCADE, related_name='user_comment')
    comment = TextField(null=False)
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created', 'user']

    def __str__(self):
        return f'Event {self.event} commented by {self.user}'

EventViewer/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm, DateTimeInput
from EventViewer.models import Event


class SignUpForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['first_name'].widget.attrs['class'] = 'form-control'
        self.fields['last_name'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'


class MyDateInput(DateTimeInput):
    input_type = 'datetime-local'

    def __int__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)


class EventForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Event
        exclude = ['user_attend','user_creator']
        widgets = {
            'start_at': MyDateInput(),
            'end_at': MyDateInput(),
        }

EventViewer/views.py
from datetime import datetime
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.paginator import Paginator
from django.db.models import Count
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import CreateView, UpdateView, DeleteView
from EventViewer.forms import SignUpForm, EventForm
from EventViewer.models import Event, Category, Comment


# Create your views here.


def home_page(request):
    events= Event.objects.filter(start_at__gte= datetime.now())[:3]
    event_tips = Event.objects.filter(start_at__gte=datetime.now()).annotate(num_attendees=Count('user_attend')).order_by('-num_attendees')[:4]
    context= {'events':events, 'event_tips': event_tips}
    return render(request, 'home.html', context)


def paginate_queryset(request, queryset, page_size):
    paginator = Paginator(queryset, page_size)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


def event_page(request):
    categories = Category.objects.all()
    events = Event.objects.filter(start_at__gte=datetime.now())
    page_obj = paginate_queryset(request, events, 20)

    context = {'page_obj': page_obj, 'categories': categories}
    return render(request, 'events.html', context)


def search_events(request):
    categories = Category.objects.all()
    if request.method == 'POST':
        search = request.POST.get('query')
        search = search.strip()
        request.session['search'] = search
    else:
        search = request.session['search']
    if len(search) > 0:
        events = Event.objects.filter(name__contains=search)
        page_obj = paginate_queryset(request, events, 20)
        if len(events) == 0:
            messages.info(request, "Can't find your event.")
        context = {'search': search, 'page_obj': page_obj, 'categories': categories}
        return render(request, 'events.html', context)
    else:
        messages.info(request, "Can't find your event.")
    return render(request, 'events.html', {'categories': categories})


def filter_events(request):
    selected_category = request.session.get('selected_category', '')
    min_price = request.session.get('min_price', '')
    max_price = request.session.get('max_price', '')
    upcoming_events = request.session.get('upcoming_events', '')
    past_events = request.session.get('past_events', '')

    categories = Category.objects.all()

    if request.method == 'POST':
        selected_category = request.POST.get('category', '')
        min_price = request.POST.get('min_price', '')
        max_price = request.POST.get('max_price', '')
        upcoming_events = request.POST.get('upcoming_events', '')
        past_events = request.POST.get('past_events', '')

        request.session['selected_category'] = selected_category
        request.session['min_price'] = min_price
        request.session['max_price'] = max_price
        request.session['upcoming_events'] = upcoming_events
        request.session['past_events'] = past_events

    events = Event.objects.all()
    if selected_category:
        events = events.filter(category=selected_category)
    if min_price:
        events = events.filter(price__gte=min_price)
    if max_price:
        events = events.filter(price__lte=max_price)
    if upcoming_events and past_events:
        events = events

    elif upcoming_events:
        events = events.filter(start_at__gt=datetime.now())
    elif past_events:
        events = events.filter(start_at__lt=datetime.now())

    if not selected_category:
        selected_category = 0

    page_obj = paginate_queryset(request, events, 20)
    if not page_obj:
        messages.info(request, "Can't find your event.")
    context = {
        'categories': categories,
        'page_obj': page_obj,
        'selected_category': int(selected_category),
        'min_price': min_price,
        'max_price': max_price,
        'upcoming_events': upcoming_events,
        'past_events': past_events,
    }
    return render(request, 'events.html', context)





@login_required
def event_detail_page(request, pk):
    event = Event.objects.get(id=pk)
    comments = Comment.objects.filter(event=event).all()
    context = {'event': event, 'comments':comments}
    return render(request, 'event_detail.html', context)


@login_required
def attend_event(request):
    if request.method == 'POST':
        pk = request.POST.get('event_id')
        event = Event.objects.get(id=pk)
        if not request.user in event.user_attend.all():
            event.user_attend.add(request.user)
            messages.success(request, "You are attending this event. Have a fun!")
        else:
            event.user_attend.remove(request.user)
            messages.info(request, "You are not attending this event.")
    return redirect(f'/event_detail/{pk}/')


@login_required
def add_comment(request, pk):
    if request.method == 'POST':
        pk = request.POST.get('event_id')
        comment = request.POST.get('comment').strip()
        if len(comment) > 0:
            Comment.objects.create(
                event = Event.objects.get(id=pk),
                user = request.user,
                comment = comment
            )
            messages.success(request, "Your comment was posted.")
        else:
            messages.error(request, "Cant post your comment.")
    return redirect(f'/event_detail/{pk}/')


@login_required
def edit_comment(request, pk):
    comment = Comment.objects.get(id=pk)
    if request.user == comment.user:
        if request.method == 'POST':
            comment_text = request.POST.get('comment').strip()
            comment.comment = comment_text
            comment.save()
            messages.info(request, "Your comment was edited.")
            return redirect(f'/event_detail/{comment.event.id}/')
        context = {'comment':comment}
        return render(request, 'event_detail.html', context)
    return redirect(f'/event_detail/{comment.event.id}/')


@login_required
def delete_comment(request, pk):
    comment = Comment.objects.get(id=pk)
    if request.user == comment.user:
        if request.method == 'POST':
            comment.delete()
            messages.info(request, "Your comment was deleted.")
            return redirect(f"/event_detail/{comment.event.id}/")

        # else
        context = {'comment': comment}
        return render(request, 'comment_confirm_delete.html', context)
    return redirect(f"/event_detail/{comment.event.id}/")


class EventCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'new_event.html'
    form_class = EventForm
    success_url = reverse_lazy('event_page')
    permission_required = 'viewer.add_event'

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user_creator = self.request.user
        obj.save()
        return super().form_valid(form)


class EventUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'new_event.html'
    model = Event
    form_class = EventForm
    permission_required = 'viewer.edit_event'

    def get_success_url(self):
        return reverse_lazy('event_detail_page', kwargs={'pk': self.object.pk})


class EventDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'event_detail.html'
    model = Event
    success_url = reverse_lazy('event_page')
    permission_required = 'viewer.delete_event'


class SignUpView(generic.CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy('home_page')
    template_name = 'signup.html'

EventViewer/templates/includes/comments.html
<div class="row d-flex justify-content-center">
    <div class="col-md-8 col-lg-6">
        <div class="card shadow-0 border" style="background-color: #C0C0C0">
            <div class="card-body p-4">
                <div class="form-outline mb-4">
                    <form method="post" action="{% url 'add_comment' pk=event.id %}">
                        {% csrf_token %}
                        <input name="comment" type="text" id="comment" class="form-control"
                               placeholder="Type comment..."/>
                        <input type="hidden" name="event_id" value="{{ event.id }}">

                        <input type="submit" class="btn btn-sm btn-success display-4" style="margin-top: 5px;">
                    </form>
                </div>

                {% for comment in comments %}
                <div class="card mb-4">
                    <div class="card-body">
                        <p>{{ comment.comment }}</p>

                        <div class="d-flex justify-content-between">
                            <div class="d-flex flex-row align-items-center">
                                <strong><p class="small mb-0 ms-2">{{ comment.user }}</p></strong>
                            </div>
                            <div class="d-flex flex-row align-items-center">
                                <p class="small text-muted mb-0">{{ comment.created }}</p>
                            </div>
                        </div>

                        {% if request.user == comment.user %}
                        <div class="d-flex flex-row-reverse">
                            <form method="post" action="{% url 'delete_comment' comment.id %}"
                                  style="margin-left: 10px;">
                                {% csrf_token %}
                                <input type="hidden" name="comment_id" value="{{ comment.id }}">
                                <div class="mbr-section-btn mt-3">
                                    <button class="btn btn-sm btn-danger">Delete</button>
                                </div>
                            </form>
                            <div class="mbr-section-btn mt-3">
                                <a href="#edit_comment_{{ comment.id }}" class="btn btn-sm btn-secondary">Edit</a>
                            </div>
                        </div>
                        <form method="post" action="{% url 'edit_comment' comment.id %}"
                              id="edit_comment_{{ comment.id }}">
                            {% csrf_token %}
                            <input type="hidden" name="comment_id" value="{{ comment.id }}">
                            <textarea class="form-control" name="comment">{{ comment.comment }}</textarea>
                            <div class="text-center mt-4">
                                <button class="btn btn-success">Save</button>
                            </div>
                        </form>
                        {% endif %}

                    </div>
                </div>
                {% endfor %}


            </div>
        </div>
    </div>
</div>

EventViewer/templates/includes/delete_confirm.html
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header border-bottom-0">
                <button type="button" class="btn-close float-end" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body text-start text-black p-4">

                <h4 class="mb-5" style="color: #35558a;">Are you sure you want to delete event '{{ event }}'?</h4>

            </div>
            <div class="modal-footer d-flex justify-content-center border-top-0 py-4">
                <form method="POST" action="{% url 'delete_event' pk=event.id %}">

                    {% csrf_token %}

                    <input type="hidden" name="next" value="{% url 'event_page' %}">
                    <button class="btn btn-lg btn-danger display-4" type="submit">Delete Event</button>


                </form>

            </div>
        </div>
    </div>
</div>

EventViewer/templates/includes/filter.html
<div class="card">
    <article class="card-group-item">
        <header class="card-header">
            <h6 class="title">Filters</h6>
        </header>

        <form method="post" action="{% url 'filter_events' %}">
            {% csrf_token %}

            <div class="card-body">

                <div class="row">
                    <div class="form-group col-md-2">
                        <label>Min Price</label>
                        <input name="min_price" type="number" class="form-control" id="min_price"
                               placeholder="{{ min_price }}">
                    </div>
                    <div class="form-group col-md-2 text-right">
                        <label>Max Price</label>
                        <input name="max_price" type="number" class="form-control" id="max_price"
                               placeholder="{{ max_price }}">
                    </div>


                    <div class="col-md-5">
                        <label>Category</label>
                        <select name="category" class="form-select" aria-label="Default select example">
                            <option value="">Select category</option>
                            {% for category in categories %}
                            {% if  selected_category == category.id %}
                            <option value="{{ category.id }}" selected>{{ category.name }}</option>
                            {% else %}
                            <option value="{{ category.id }}">{{ category.name }}</option>
                            {% endif %}
                            {% endfor %}
                        </select>
                    </div>

                    <div class="col-md-2 d-flex align-items-center">
                        <div class="custom-control custom-checkbox">
                            {% if upcoming_events %}
                            <input name="upcoming_events" type="checkbox" class="custom-control-input" id="Check1"
                                   checked>
                            {% else %}
                            <input name="upcoming_events" type="checkbox" class="custom-control-input" id="Check1">
                            {% endif %}
                            <label class="custom-control-label" for="Check1">Upcoming events</label>
                        </div>
                        <div class="custom-control custom-checkbox ml-3">
                            {% if past_events %}
                            <input name="past_events" type="checkbox" class="custom-control-input" id="Check2" checked>
                            {% else %}
                            <input name="past_events" type="checkbox" class="custom-control-input" id="Check2">
                            {% endif %}
                            <label class="custom-control-label" for="Check2">Past events</label>
                        </div>

                    </div>
                    <div class="col-md-1">
                        <button type="submit" class="btn btn-lg btn-secondary" style="margin-top: 10px">Filter</button>
                    </div>
                </div>
            </div>

        </form>
    </article>
</div>

EventViewer/templates/includes/messages.html
{% if messages %}
{% for message in messages %}
<div class="container-fluid p-0">

    <div class="alert {{ message.tags }}">
        <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close">
        </button>
        {{ message }}
    </div>
</div>
{% endfor %}
{% endif %}

EventViewer/templates/includes/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg" style="background-color: #C0C0C0">
    <div class="container-fluid">

        <a class="navbar-brand" href="{% url 'home_page' %}">
            <img src="{% static 'uniswap.svg' %}" width="50" height="50" alt="">
        </a>

        <a class="navbar-brand" href="{% url 'home_page' %}">Event Aggregation Service</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home_page' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'event_page' %}">Events</a>
                </li>

                {% if user.is_superuser or perms.store.viewer.add_event %}
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'new_event' %}">Add Event</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'api:get_events' %}">API</a>
                </li>
                {% endif%}


            </ul>



            <form class="d-flex me-auto" role="search" method="POST" action="{% url 'search_events' %}">
                {% csrf_token %}
                <input class="form-control me-2" type="text" placeholder="Search" aria-label="Search" name="query">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>



            <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                {% if request.user.is_authenticated %}

                <li class="nav-item">
                    <a class="nav-link active" href=""><strong>{{ request.user.username }}</strong></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'logout' %}">Log Out</a>
                </li>

                {% else %}
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'signup'%}">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'login' %}">Log In</a>
                </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>